---
version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  test:
    docker:
      - image: circleci/ruby:2.6.3-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run: bundle exec rspec -fd

  test_with_elastic:
    environment:
      ELASTIC_SEARCH_VERSION: '6.2.3'
    docker:
      - image: circleci/ruby:2.6.3-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Install Elastic Search
          command: ./script/install_elasticsearch.sh
      - run: bundle exec rspec -fd --tag elasticsearch spec/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - test_with_elastic
